### ISSUE TITLE
Missing frame_id for the published attitude/euler message 

### ISSUE THREAD

**Issue by sayali-purdue** [rosflight/rosflight_ros_pkgs#142]
No `frame_id` field has been set for the `euler_msg` (of type geometry_msgs::Vector3Stamped) that is published at line 439 in [rosflight_io.cpp](https://github.com/rosflight/rosflight/blob/master/rosflight/src/rosflight_io.cpp#L439). I believe that coordinate frame information of the published data would be useful to other users of the node, makes code more readable.

**Comment by superjax** [comment]
Could be!  Feel free to submit a PR! :wink:
