### ISSUE TITLE
Easier compilation on arm64

### ISSUE THREAD

**Issue by bsutherland333** [rosflight/rosflight_ros_pkgs#154]
rosflight_ros_pkgs currently can't be compiled on arm64 devices, due to Gazebo not having an arm64 target. Enabling some way to still be able to use the functionality that should exist on arm64 devices (rosflight_io, rosflight_utils) while still following the same compilation procedure would make things much simpler on arm64 devices.

**Comment by JMoore5353** [comment]
I put compilation checks in the CMakeLists of rosplane_sim and rosflight_sim packages to skip compilation if the architecture is arm64. I also updated our Dockerfile to skip the rosdep keys related to gazebo if the architecture is arm64.

**Comment by bsutherland333** [comment]
Could you also update the webpage documentation?
