### ISSUE TITLE
Create Anaconda parameters for ROSflight simulation

### ISSUE THREAD

**Issue by bsutherland333** [rosflight/rosflight_ros_pkgs#158]
Our current airframe has not been working well for autonomous flight due to an unsteady roll axis in flight. To fix this, we are going to switch to the RMRC Anaconda, which has already been proven by our lab and others to work well as a research platform. 

As part of this, we need to implement updated dynamic parameters in the simulation for the Anaconda.

**Comment by iandareid** [comment]
The parameters have been added to rosflight_sim. They are based off of a system identification paper used for the anaconda. Looking forward we will be refining these aerodynamic parameters based on AVL and CIFER tests.
