### ISSUE TITLE
Parameter file for default fixed-wing settings

### ISSUE THREAD

**Issue by dpkoch** [rosflight/rosflight_ros_pkgs#79]
There are a few parameters that need to be changed by default. I wonder if it'd be helpful to add a small parameter file that sets those defaults, which the user can then set with `rosservice call /param_load_from_file /path/to/params.yaml`? The path is going to be a little funky, like `/opt/ros/melodic/share/rosflight/params/fixedwing.yaml` or something so it's not super clean, but maybe helpful?

**Comment by bsutherland333** [comment]
A default parameter file now exists in rosflight_utils/params.
